version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: beefshop-backend
    ports:
      - "8888:8888"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: oungbeefshopsql
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: beefshop-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: oungbeefshopsql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
